[package]

name = "ndarray"
version = "0.11.2"
authors = ["bluss"]
license = "MIT/Apache-2.0"
readme = "README-crates.io.md"

repository = "https://github.com/bluss/rust-ndarray"
documentation = "https://docs.rs/ndarray/"

description = "An n-dimensional array for general elements and for numerics. Lightweight array views and slicing; views support chunking and splitting."

keywords = ["array", "data-structure", "multidimensional", "matrix", "blas"]
categories = ["data-structures", "science"]

build = "build.rs"

exclude = ["docgen/images/*"]

[lib]
name = "ndarray"
bench = false
test = true

[dependencies]
num-integer = { version = "0.1.32", default-features = false }
num-traits = { version = "0.1.32", default-features = false }
num-complex = { version = "0.1.32", default-features = false }
rustc-serialize = { version = "0.3.20", optional = true }
itertools = { version = "0.7.0", default-features = false }

# Use via the `blas` crate feature!
cblas-sys = { version = "0.1.4", optional = true, default-features = false }
blas-src = { version = "0.1.2", optional = true, default-features = false }

matrixmultiply = { version = "0.1.13" }
# Use via the `serde-1` crate feature!
serde = { version = "1.0", optional = true }

[dev-dependencies]
defmac = "0.1"
quickcheck = "0.5"
rawpointer = "0.1"

[features]
# Enable blas usage
# See README for more instructions
blas = ["cblas-sys", "blas-src"]

# Serde 1.0
serde-1 = ["serde"]

# These features are used for testing
test-blas-openblas-sys = ["blas"]
test = ["test-blas-openblas-sys"]

# This feature is used for docs
docs = ["rustc-serialize", "serde-1"]

[profile.release]
[profile.bench]
debug = true

[workspace]
members = ["parallel", "ndarray-rand", "serialization-tests", "blas-tests"]
exclude = ["numeric-tests"]

[package.metadata.release]
no-dev-version = true

[package.metadata.docs.rs]
features = ["docs"]
